### PR TITLE
Use em dash in home title

### PR DESCRIPTION
**Pull request by jurf**
Yay, Unicode!

### CODE REVIEW

**Comment by jurf** [comment]
Also, flatpak.org’s title is ‘Flatpak—the future of application distribution’, but Flathubs’s is ‘Flathub—An app store and build service for Linux’ – notice the different capitilisation, we should probably decide on which to use.

**Comment by jgarciao** [comment]
Hi Juraj. First of all thanks for taking time to contribute to this project. I've looked a little bit and apparently the most common title separators are the bar "|",  dash "-" and colon ":"

- https://northward.io/articles/title-separator-symbols
- https://www.chrisains.com/seo/how-to-structure-title-tags-for-seo/

What is the benefit of using an em-dash?

**Comment by jurf** [comment]
Easy. You’ve picked a dash (which the logical choice IMO, since it’s basically a subtitle) except that you didn’t – ‘-’ is a _hyphen_, not a dash. A dash looks like this ‘–’ (British English) or this ‘—’ (US English). We use US English so I just changed it to that. If you want another separator, that’s fine by me, I’m just here for the correct typography.

**Comment by jurf** [comment]
I’m on mobile and under time stress so I can’t really source my info, but no, a hyphen is a hyphen, a dash is a dash. en_US uses an em-dash, en_GB uses an en-dash. Using a hyphen as a dash a typewriter age relic, just as using two hyphens, and it’s really sad to see how the most popular sites on the internet fail to utilise basic typographical (and actually grammatical) rules. There are exceptions however, e.g. GitHub.

(Rant over. Sorry, I get emotional with typography :-)

I am pretty sure this way is correct. Spaces are optional, personally I don’t like using them with em-dashes (neither does GitHub btw). I am working on more things related to typography and style in general on this site, I’ll keep you posted. :-)

Thanks for your time.

**Pull request merged**
