### PR TITLE
theme: avoid dropshadows

### PR DESCRIPTION
**Pull request by jimmac**
- override the styles in flathub-theme

https://github.com/flathub/linux-store-frontend/issues/72

### CODE REVIEW

**Comment by jgarciao** [comment]
I'm not so sure about converting the website to a "flat design". I'm using  the [Angular Material](https://material.angular.io/components/categories) components, which implement Google's Material Design. They use [elevation and shadows](https://material.io/guidelines/material-design/elevation-shadows.html) _to form a spatial model that is familiar to users and can be applied consistently across apps._ 

If we begin to make changes to the buttons or tiles to make them "flat" we will have to eventually make everything flat for consistency, and that will mean battling with Angular Material CSS which I personally I don't want to do because it will decrease my productivity and probably will end up with a worse product. It will also make the website more difficult to maintain, as Angular Material component library is updated often.

As an example, your change "fixed" the blue buttons in the homepage but broke the "Website" buttons in the app details page.

We can talk about it but this is my opinion right now

app-details-website-flat-button

**Comment by jimmac** [comment]
We are not Android. The original site shaded the bottom edge of the buttons to signify some affordance. I'll add that back.

**Comment by jgarciao** [comment]
I found this that could help configuring the shadows as you want and being more angular material friendly:

https://material.angular.io/guide/elevation

**Comment by jgarciao** [comment]
I'm closing this as the style remained as it was. Thanks a lot for your contributions anyway and sorry for having this pending for so long

**Pull request closed without merging**
