### PR TITLE
Show a "new" label or icon in apps added recently

### PR DESCRIPTION
**Pull request by antoniorsz**
As per #93 
It does work but I'd wait till #98 is merged so we could use material's built in [badges](https://material.angular.io/components/badge/overview).
So this is just a proposition of how I see it implemented.

### CODE REVIEW

**Comment by jgarciao** [comment]
I would like to add a tag only on new apps (not updated) and not as prominent as your proposal.  I just merged #98 so maybe with angular badges will look better.

This kind of icons could be an option too:
- https://fontawesome.com/icons/tag?style=solid
- https://fontawesome.com/icons/certificate?style=solid   (with "NEW" inside)

**Comment by antoniorsz** [comment]
I made it smaller, inside the card and removed it from recently updated apps.
Unfortunately material's badges support only text inside them. As of 6.0.1 you can not fit in there mat-icon.

**Comment by jgarciao** [comment]
I've change the color for "primary" and added a little padding

Thanks for contributing!

**Comment by jgarciao** [comment]
I realized that I never told you that the "new" badges weren't activated because the designers (and me) weren't sure about this icon and we are holding this functionality until a complete new badge design is created.  Your code will probably be used to implement the new design

Thanks again for contributing!

**Pull request merged**
