### PR TITLE
Upgrade to Angular 6

### PR DESCRIPTION
**Pull request by splitt3r**
See https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4 for details.

### CODE REVIEW

**Comment by jgarciao** [comment]
I was aware to the release (I've been looking for it for the last two weeks) but I was waiting for the first micro release to avoid some errors.

Did you have many warnings running ng update? I was expecting Angular Material complaining a lot about deprecated stuff...

**Comment by splitt3r** [comment]
I did it partly by hand because ng update didn´t work for any of my projects completely 😞 but so far everything looks good and only had to change the rxjs imports.

**Comment by splitt3r** [comment]
Everything looks nice and smooth :) I think we could give it a try but if you want to wait simply close the pr :stuck_out_tongue:

**Comment by jgarciao** [comment]
I think it's better to do a micro release this/next week with minor changes ([copy button](https://github.com/flathub/linux-store-frontend/pull/97), update popular apps, ...) and then merge this PR

**Comment by splitt3r** [comment]
Sounds good to me :+1:

**Pull request merged**
