### PR TITLE
 Replace Google Analytics with basic Matomo tracking 

### PR DESCRIPTION
**Pull request by barthalion**

### CODE REVIEW

**Comment by barthalion** [comment]
FYI @jgarciao 

I would like to merge it this week. We should probably regenerate popular applications while data in GA is still up to date.

**Comment by barthalion** [comment]
FYI @jgarciao 

I would like to merge it this week. Can you also update popular application's list basing on latest data in GA?

**Comment by barthalion** [comment]
Alternatively I can handle that myself if you grant access to `barthalion@gmail.com`.

**Comment by jgarciao** [comment]
Hi Bartłomiej. I just gave you access to GA.

I would like to activate Matomo now and GA at the same time to compare for a couple of weeks to see the differences in the traking numbers and just use Matomo in 2020. 

Let me take a look at the code tonight and let's try to deploy it tomorrow morning (or next Monday, in case you are available)

**Comment by barthalion** [comment]
Sounds good! It will deploy automatically when you merge my changes (or push anything else) to master.

**Comment by jgarciao** [comment]
Closing this because we added Matomo support in version 0.7.4

**Pull request closed without merging**
