### PR TITLE
Add copy button to installation. 

### PR DESCRIPTION
**Pull request by antoniorsz**
As mentioned in issue #91

### CODE REVIEW

**Comment by jgarciao** [comment]
I'm trying a refactored version in the [test sever](http://45.55.104.129/apps/details/org.gimp.GIMP). There is still a little bug to solve (icon is not shown in Gnome Web) but I will fix it and merge it soon.

Thanks for your contribution!

**Comment by antoniorsz** [comment]
Icons not showing in epiphany is not related to these changes, they don't show at all in this project. I tried pinning down what the reason but havn't figured it out yet.
Don't merge this just yet, after I made this request I found similar pre tag with installation instructions in AboutComponent so I'll add changes there too.

**Comment by jgarciao** [comment]
Please, don't modify AboutComponent yet. The refactoring I've done is to
make a shared store-pre component that wraps the functionality that you
have developed. We can use this component in AboutComponent

El dt., 8 de maig 2018, 08:07, antoniorsz <notifications@github.com> va
escriure:

**Comment by antoniorsz** [comment]
That's exactly what i had in mind

**Comment by jgarciao** [comment]
I couldn't merge this PR because I think you made the changes from the beta.flathub.org branch, which is used only for publishing at flathub.org  (I will change the name to avoid confusion)

I've cherry-picked your commit and make the refactoring in the master branch.

Thanks again for your contribution!

**Pull request closed without merging**
