### PR TITLE
Check for Creative Commons licenses with NonCommercial clause.

### PR DESCRIPTION
**Pull request by rrigby**
Licenses with this clause are NonFree. If you've got a line length policy and would prefer a break line let me know.

### CODE REVIEW

**Comment by rrigby** [comment]
Following the GNU philosophy it is proprietary, because it does not meet the four freedoms. 

https://www.gnu.org/proprietary/proprietary.en.html

Following the OSI philosophy it is not Open Source because it does not meet their definition

https://opensource.org/osd

Additionally the CC-BY-NC softwares on flathub don't provide any sources anyway. To not cause confusion to the user (I'm sure trickery is their aim using a restrictive CC license) I'd recommend just labelling them proprietary.

**Comment by TingPing** [comment]
> Additionally the CC-BY-NC softwares on flathub don't provide any sources anyway. 

That is just a packaging oversight really.

**Comment by rrigby** [comment]
No the applications do not provide sources anywhere. They are not 'source-available'.

**Comment by TingPing** [comment]
Oh, then yea those are certainly proprietary. I don't think CC-BY-NC *code* should be labeled proprietary though.

**Comment by rrigby** [comment]
I do. Because it is.

**Comment by jgarciao** [comment]
Most of the users when installing this program will click on the INSTALL button and Gnome Software will show again the info for the app.

For consistency I will try to show the same license information than Gnome Software

**Comment by jgarciao** [comment]
This PR is no longer needed after merging this https://github.com/flathub/linux-store-frontend/pull/161
 
Thanks for your contribution anyway @rrigby!

**Pull request closed without merging**
