### PR TITLE
Fix 404 error pages

### PR DESCRIPTION
**Pull request by flyingpimonster**
- Show a 404 page for nonexistent URLs, rather than redirecting to a blank page.
- Add a separate App Not Found screen for when an app detail URL is correctly formed, but the app ID is not found. This replaces the old behavior, which was to redirect to /not-found. This is better because it doesn't replace the URL and it gives more specific error information.

### CODE REVIEW

**Comment by jgarciao** [comment]
Hi. Thanks for your contribution. If I find time I'll try it this weekend

**Comment by barthalion** [comment]
cc @iamjahoo

**Comment by barthalion** [comment]
@flyingpimonster Mind checking if I didn't butcher anything when resolving merge conflict?

**Comment by IAmJahoo** [comment]
@flyingpimonster, works brilliant right now, good job 💪

**Pull request merged**
