### PR TITLE
Search cosmetics enhancement

### LINKED ISSUE #320: clicking the magnifying glass doesn't focus the search input field
Open flathub.org in Firefox or chromium-browser, and click the magnifying glass icon in the header.
A text field appears with "Search apps" placeholder text, but this does not have the input focus. You have to click a second time to type anything into it, or press [Shift+Tab] to move the focus to it A minor detail, but it feels weird.

Looking at the HTML for the search box,
```html
<input _ngcontent-bgw-c94="" id="search-box" type="search" placeholder="Search apps"
   autofocus="" autocapitalize="none" class="search-box">
```
you would think the `autofocus=""` would put the input focus there.

In fact, if you bring up a flathub page and immediately type BAZINGA, then click the magnifying glass, the search box appears with your typed text in it. So the initial input focus is set to this invisible field (you can [Tab] and [Shift+Tab] from it to the magnifying glass and 3-dot menu), but when you click on the magnifying glass, your keyboard focus doesn't return to the search box. After clicking the magnifying glass, typing **document.activeElement** in the browser developer tools console displays `<button _ngcontent-bgw-c94="" mat-icon-button="" class="mat-focus-indicator ...">`, not the `input#search-box.search-box`. If you tab backwards and forwards you can see the input focus ring highlight "behind" the search box where the magnifying glass was visible.

### PR DESCRIPTION
**Pull request by ralphocdol**
Cosmetic fixes on small screens

1. Focus search input after clicking the magnifying glass
2. On first load, show search box when typing

Fixes #320

### CODE REVIEW

**Comment by ralphocdol** [comment]
Resolves: #320

**Comment by razzeee** [comment]
The old website is hopefully EOL soon, so we're probably not going to merge anything here anymore.

**Comment by JakobDev** [comment]
@razzeee Is there alreday a preview or source for the new Website aviable?

**Comment by ralphocdol** [comment]
> The old website is hopefully EOL soon, so we're probably not going to merge anything here anymore.

Wait, I've never heard of this, where's the new website? Or the announcement at least?

**Comment by razzeee** [comment]
https://github.com/flathub/backend/
https://github.com/flathub/frontend

You can find a sort of preview here on my vercel https://flathub.vercel.app/ but that's not an official place. Just so you know.

**Comment by ralphocdol** [comment]
> https://github.com/flathub/backend/ https://github.com/flathub/frontend
> 
> You can find a sort of preview here on my vercel https://flathub.vercel.app/ but that's not an official place. Just so you know.

Looks nice and smooth with [Next.js](https://github.com/vercel/next.js)

**Pull request closed without merging**
