### PR TITLE
Change to show the license if the app is not proprietary

### LINKED ISSUE #143: License: 'Free' is ambiguous
Even if flatpak provides better sandboxing capabilities than previous package management systems in Linux, I want to know if the software I'm installing is opensource or not.

When the "License" field contains "Free", this is clearly ambiguous, because what does this exactly mean? Free as in beer (free-ware) or free as in freedom(FLOSS)? Please make this explicit. A way to do this would be to mention the specific name of the license. Or if this is too technical, just mention if the licence is approved by the OSI or FSF.

One example where this is not explicit: https://flathub.org/apps/details/org.gimp.GIMP

### PR DESCRIPTION
**Pull request by Dafnik**
This pull request fixes #143.

If the app is open source it will show the right license.

### CODE REVIEW

**Comment by Dafnik** [comment]
I'm also open to changing the behaviour to the one of Gnome Softwares with a popup.

**Comment by jgarciao** [comment]
This is the behavior that the application had at the beginning, but it doesn't work well because some apps have more than one license and it doesn't look good

Darktable, for example, has this value in the license field: 
GPL-3.0+ and GPL-2.0+ and LGPL-2.0+ and BSD-3-Clause and MIT and CC-BY-SA-1.0 and CC-BY-2.5 and CC-BY-NC-3.0

A [dialog](https://v6.material.angular.io/components/dialog/overview) or [expansion panel](https://v6.material.angular.io/components/expansion/overview) might be better

**Comment by Dafnik** [comment]
I will take a look into it.

**Comment by Dafnik** [comment]
Here is what a proprietary app looks like: 
Picture

And here is what a open source app looks like:
Picture
Picture

**Comment by jgarciao** [comment]
It looks nice (in the screenshot) but if you don't mind I prefer not to mark proprietary software in red. Maybe both could be regular buttons

**Comment by Dafnik** [comment]
Any news for my questions?

**Comment by jgarciao** [comment]
Sorry, I'm a little busy this week and I work on Flathub only on my spare time. I will finish the last details and let you know when is deployed in the dev server.

Thanks for your contribution!

**Comment by Dafnik** [comment]
Any news on this?

**Comment by jgarciao** [comment]
Sorry, I apologize. I've been involved in other stuff and I couldn't find the time to properly merge this and add the last touches. I don't think I'm going to be able to do it until April

**Comment by jgarciao** [comment]
This is how it works now:

- Proprietary Apps: just show Proprietary  (example: [Spotify](http://45.55.104.129/apps/details/com.spotify.Client))
- Open source apps with short license value: show the license(s)  (example: [GIMP](http://45.55.104.129/apps/details/org.gimp.GIMP))
- Open source apps with long license value: show dialog (example: [Darktable](http://45.55.104.129/apps/details/org.darktable.Darktable))

Thanks for your contribution @Dafnik

**Pull request merged**
