### PR TITLE
Suggest the usage of node 14.X in README

### PR DESCRIPTION
**Pull request by razzeee**
This updates the stack to angular 12, with the help of https://update.angular.io/

This drops support for IE11 and before.
And will need at least node 12, so I've based that on @jgarciao PR

I've had a quick look and it seems to have not broken anything.

Next thing to do would be to move from tslint to eslint.

### CODE REVIEW

**Comment by barthalion** [comment]
Last time I reverted the Angular upgrade because search bar was broken. Let's see how it goes this time.

**Comment by razzeee** [comment]
Oh, I could have specifically tested that, if you would have let me known :)

**Comment by barthalion** [comment]
Just tested it and it actually works this time. :) Thanks a lot.

**Comment by razzeee** [comment]
Nice, I'll try to do the porting from tslint to eslint then

**Pull request merged**
