### PR TITLE
Make the install button a link too

### PR DESCRIPTION
**Pull request by takluyver**

### CODE REVIEW

**Comment by takluyver** [comment]
OK, now I'm quite confused. I assumed that the flatpakref files would be served by the [backend](https://github.com/flathub/linux-store-backend), but it looks like the directory is mounted for the frontend server, so maybe they're served as part of the frontend? There's some nginx config in the repo, so maybe it's just a matter of adding `application/vnd.flatpak.ref   flatpakref;` to [this file](https://github.com/flathub/linux-store-frontend/blob/master/conf/nginx/mime.types)?

**Comment by jgarciao** [comment]
The reason I used this kind of button + FileSaver.js  was to overcome this problem (see #23). Maybe with the change in the configuration of nginx will work properly with a regular link. I will try in my dev server and tell @ramcq  if it works fine.

There is a more proper way (see docs [here](https://material.angular.io/components/button/examples)) to a make the button a regular link (pending is how to send the Install event to Google Analytics):
`<a mat-raised-button href="{{app.downloadFlatpakRefUrl}}">Install</a>`

**Comment by takluyver** [comment]
:+1: if the server can send the right mimetype, then I agree it's best to get rid of the JS click handling entirely. Did I understand right that the flatpakref files are being served by nginx?

**Comment by jgarciao** [comment]
Yes, they are served by nginx, same as the screenshots and icons. The nginx file in linux-store-backend is used only for the docker image I use in my dev server, not in flathub.org

**Comment by takluyver** [comment]
Do you mean in linux-store-frontend? I don't see any nginx config in -backend. Is the nginx config used for the main flathub.org site in any of the repositories?

I've changed the HTML as you suggested, but left the JS click handler alone for now. If you find that changing the HTTP server config to send the right mimetype makes things work, I can get rid of the FileSaver code too.

**Comment by takluyver** [comment]
Thanks! Did you figure anything out about the mimetypes on the server side?

**Comment by jgarciao** [comment]
In the end I changed the [nginx mime type configuration](https://github.com/flathub/linux-store-frontend/commit/ff2678f45cb960919e8ccd2e4e27fe15cb2d4810) as you suggested and additionally I [added a download atribute](https://github.com/flathub/linux-store-frontend/commit/00cf470505f44860b97d116bb9816b32a75f45b6) to the link. 

The version with your changes is online since last Thursday. Thanks for your contribution!

**Comment by takluyver** [comment]
:+1: just checked, and the install button is working nicely now. Thanks!

**Pull request merged**
