### PR TITLE
Remove google analytics and browser-update.org

### PR DESCRIPTION
**Pull request by jgarciao**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I guess its ready to be merged?

**Comment by jgarciao** [comment]
It should work but I didn't want to just merge it myself in holiday season
in case something happens.

El dl., 28 de des. 2020, 20:25, Bilal Elmoussaoui <notifications@github.com>
va escriure:

**Comment by bilelmoussaoui** [comment]
I guess at worst, I will revert it. Very happy to see Google Analytics out :)

**Comment by jgarciao** [comment]
Alfter control+F5 seems to work fine on Firefox and Google Chrome and Ghostery shows only Matono as a tracker. Thanks Bilal!

**Pull request merged**
