### PR TITLE
Update angular

### LINKED ISSUE #253: Angular version is outdated
The app is currently on versión 6 of the Angular framework which is no longer supported.

https://angular.io/guide/releases

### PR DESCRIPTION
**Pull request by itea-dev**
Updates Angular from version 6 to 10 and other dependencies in the project.

Fixes #253

### CODE REVIEW

**Comment by barthalion** [comment]
cc @iamjahoo

**Comment by barthalion** [comment]
@itea-dev I'm not sure if it's browser misconfiguration on my side, but since the upgrade search icon no always shows up:

image

I assume it has something to do with my poor attempt to preload fonts via https://github.com/flathub/linux-store-frontend/commit/6205abf0cd544235d7b29c9d5f11dbbcfe6bf09e and https://github.com/flathub/linux-store-frontend/commit/74225779c9e522ab4a78d6e5ba7a492985dd9c2f – but my Javascript knowledge ends at putting semicolons at the end of the line so I wouldn't mind some help!

**Comment by itea-dev** [comment]
@barthalion 

I don't see that issue on my side when I load flathub.org and on dev server. Could you try again and reload the page?

image

**Comment by barthalion** [comment]
Yeah, it seems to work fine on refresh/next visits, just the first time is wrong.

**Pull request merged**
